name: Publish on Release

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2' # the full version of `docker-compose` command

      - name: Install dependencies
        run: bun install

      - name: Build and Publish
        run: bun prepublish && npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
